### ISSUE TITLE
Welcome to Messier

### ISSUE THREAD

**Issue by everettjf** [messier-app/messier#1]

**Comment by josercc** [comment]
@everettjf 这个 Messier.framework 集成在 App 里面是没办法上架的对吗 有什么办法可以在 Release 去除吗？

**Comment by everettjf** [comment]
@josercc 如果配合公司的CI或者编译脚本，release去除可以在这些脚本里做。

**Comment by josercc** [comment]
能提供脚本代码参考吗

**Comment by everettjf** [comment]
@josercc 没有现成的代码，但肯定可行。参考这个库 https://github.com/CocoaPods/Xcodeproj
